name: Fetch Flight Data

on:
  schedule:
    - cron: "0 12 * * *"   # runs every day at 12:00 UTC
  workflow_dispatch:        # lets you trigger manually

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install requests pandas

      # 4. Run the data collection script
      - name: Run script
        env:
          AMADEUS_KEY: ${{ secrets.AMADEUS_KEY }}
          AMADEUS_SECRET: ${{ secrets.AMADEUS_SECRET }}
        run: python scripts/data_collection.py

      # 5a. Stage and commit the CSV
      - name: Stage and commit CSV
        run: |
          git add data/raw/*.csv
          git commit -m "Automated daily flight data update [skip ci]" || echo "No changes"

      # 5b. Push changes using GitHub Action
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: main
          force: true
          github_token: ${{ secrets.GH_PAT }}

