name: Fetch Flight Data

on:
  schedule:
    - cron: "0 12 * * *"   # runs every day at 12:00 UTC
  workflow_dispatch:        # lets you trigger manually

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests pandas

      - name: Run script
        env:
          AMADEUS_KEY: ${{ secrets.AMADEUS_KEY }}
          AMADEUS_SECRET: ${{ secrets.AMADEUS_SECRET }}
        run: python scripts/data_collection.py

      - name: Commit and push results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/raw/*.csv
          git commit -m "Automated daily flight data update [skip ci]" || echo "No changes"
          # Remove old remote to avoid cached credentials
          git remote remove origin
          # Add remote with your GH_PAT
          git remote add origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/williamervin7/Airline-Flight-Price-Analysis-with-APIs-Azure.git
          # Push changes
          git push -u origin main

